name: Terraform Provider Tests

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
  pull_request:
    paths:
      - "main.go"
      - "internal/**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/provider-tests.yml"
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod tidy
      - run: go mod download
      - run: go build -v .

  docs:
    name: Docs Test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
        id: go
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: "3.x"
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_wrapper: false
      - name: Check if docs are up-to-date
        run: |
          task docs
          git diff
          BADDOCS=$(git status --porcelain)
          test -z "$BADDOCS" || (echo -e "documentation needs regenerating using task docs: $BADDOCS"; exit 1)

  unit-tests:
    name: Unit Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
        id: go
      - name: Tests
        run:
          go test -v -cover -failfast ./internal/utils

  # Run acceptance tests in a matrix with Terraform CLI versions
  provider-tests:
    name: Terraform Provider Acceptance Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - '1.5.7'
          - '1.7.5'
          - '1.9.8'
          - '1.10.5'
          - '1.11.4'
          - '1.12.2'
          - '1.14.3'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: "3.x"
      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - name: Run Acceptance Tests
        env:
          TF_ACC: "1"
          ARMIS_API_URL: ${{ secrets.ARMIS_API_URL }}
          ARMIS_API_KEY: ${{ secrets.ARMIS_API_KEY }}
        run: go test -v ./internal/provider/
        timeout-minutes: 10

  # Run sweeper after all test matrix jobs complete
  cleanup:
    name: Cleanup Dangling Resources
    needs: provider-tests
    runs-on: ubuntu-latest
    if: always()
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: "3.x"
      - run: go mod download
      - name: Run Sweeper
        env:
          TF_ACC: "1"
          ARMIS_API_URL: ${{ secrets.ARMIS_API_URL }}
          ARMIS_API_KEY: ${{ secrets.ARMIS_API_KEY }}
        run: task sweep
